/* eslint-disable */
// Generated by generate-api-types.ts. DO NOT EDIT MANUALLY.

export type ReportEventV1Params = Record<string, never>;

export type GetClientVersionV1Params = Record<string, never>;

export type GetServerVersionV1Params = Record<string, never>;

export type GetBucketizedDataV1Params = {
  leaderboardName: string;
};

export type GetAppListV1Params = Record<string, never>;

export type GetAppListV2Params = Record<string, never>;

export type GetSDRConfigV1Params = {
  appid: number;
};

export type GetServersAtAddressV1Params = {
  addr: string;
};

export type UpToDateCheckV1Params = {
  appid: number;
  version: number;
};

export type PlayerStatsV1Params = Record<string, never>;

export type ViewerHeartbeatV1Params = {
  steamid: number;
  sessionid: number;
  token: number;
  stream?: any | undefined;
};

export type GetCMListV1Params = {
  cellid: number;
  maxcount?: number | undefined;
};

export type GetCMListForConnectV1Params = {
  cellid?: number | undefined;
  cmtype?: string | undefined;
  realm?: string | undefined;
  maxcount?: number | undefined;
  qoslevel?: number | undefined;
};

export type GetSteamPipeDomainsV1Params = Record<string, never>;

export type GetNewsForAppV1Params = {
  appid: number;
  maxlength?: number | undefined;
  enddate?: number | undefined;
  count?: number | undefined;
  tags?: string | undefined;
};

export type GetNewsForAppV2Params = {
  appid: number;
  maxlength?: number | undefined;
  enddate?: number | undefined;
  count?: number | undefined;
  feeds?: string | undefined;
  tags?: string | undefined;
};

export type GetCollectionDetailsV1Params = {
  collectioncount: number;
  'publishedfileids[0]': number;
};

export type GetPublishedFileDetailsV1Params = {
  itemcount: number;
  'publishedfileids[0]': number;
};

export type GetTokenDetailsV1Params = {
  access_token: string;
};

export type GetGlobalAchievementPercentagesForAppV1Params = {
  gameid: number;
};

export type GetGlobalAchievementPercentagesForAppV2Params = {
  gameid: number;
};

export type GetGlobalStatsForGameV1Params = {
  appid: number;
  count: number;
  'name[0]': string;
  startdate?: number | undefined;
  enddate?: number | undefined;
};

export type GetNumberOfCurrentPlayersV1Params = {
  appid: number;
};

export type GetServerInfoV1Params = Record<string, never>;

export type GetSupportedAPIListV1Params = {
  key?: string | undefined;
};

export type GetWorldStatusV1Params = Record<string, never>;

export type PollAuthSessionStatusV1Params = {
  client_id: number;
  request_id: string;
  token_to_revoke: number;
};

export type GetAuthSessionInfoV1Params = {
  client_id: number;
};

export type GetAuthSessionRiskInfoV1Params = {
  client_id: number;
  language: number;
};

export type NotifyRiskQuizResultsV1Params = {
  client_id: number;
  results: any;
  selected_action: string;
  did_confirm_login: boolean;
};

export type GetPasswordRSAPublicKeyV1Params = {
  account_name: string;
};

export type BeginAuthSessionViaCredentialsV1Params = {
  device_friendly_name: string;
  account_name: string;
  encrypted_password: string;
  encryption_timestamp: number;
  remember_login: boolean;
  platform_type: any;
  persistence?: any | undefined;
  website_id?: string | undefined;
  device_details: any;
  guard_data: string;
  language: number;
  qos_level?: any | undefined;
};

export type UpdateAuthSessionWithSteamGuardCodeV1Params = {
  client_id: number;
  steamid: number;
  code: string;
  code_type: any;
};

export type BeginAuthSessionViaQRV1Params = {
  device_friendly_name: string;
  platform_type: any;
  device_details: any;
  website_id?: string | undefined;
};

export type UpdateAuthSessionWithMobileConfirmationV1Params = {
  version: any;
  client_id: number;
  steamid: number;
  signature: string;
  confirm?: boolean | undefined;
  persistence?: any | undefined;
};

export type PostGameDataFrameRTMPV1Params = {
  appid: number;
  steamid: number;
  rtmp_token: string;
  frame_data: string;
};

export type GetCDNForVideoV1Params = {
  property_type: any;
  client_ip: string;
  client_region: string;
};

export type PickSingleContentServerV1Params = {
  property_type: any;
  cell_id: number;
  client_ip: string;
};

export type GetServersForSteamPipeV1Params = {
  cell_id: number;
  max_servers?: number | undefined;
  ip_override?: string | undefined;
  launcher_type?: any | undefined;
  ipv6_public?: string | undefined;
  current_connections: any;
};

export type GetClientUpdateHostsV1Params = {
  cached_signature: string;
};

export type GetDepotPatchInfoV1Params = {
  appid: number;
  depotid: number;
  source_manifestid: number;
  target_manifestid: number;
};

export type GetUserVoteSummaryV1Params = {
  publishedfileids: number;
};

export type RecordOfflinePlaytimeV1Params = {
  steamid: number;
  ticket: string;
  play_sessions: any;
};

export type UserCreateSessionV1Params = {
  appid: number;
  context: number;
  title: any;
  users: any;
  steamid: number;
};

export type UserUpdateSessionV1Params = {
  sessionid: number;
  appid: number;
  title: any;
  users: any;
  steamid: number;
};

export type UserDeleteSessionV1Params = {
  sessionid: number;
  appid: number;
  steamid: number;
};

export type GetWishlistSortedFilteredV1Params = {
  steamid: number;
  context: any;
  data_request: any;
  sort_order?: any | undefined;
  filters: any;
  start_index?: any | undefined;
  page_size?: any | undefined;
};

export type GetWishlistV1Params = {
  steamid: number;
};

export type GetWishlistItemCountV1Params = {
  steamid: number;
};

export type GetGamesFollowedV1Params = {
  steamid: number;
};

export type GetGamesFollowedCountV1Params = {
  steamid: number;
};

export type GetRecommendedTagsForUserV1Params = {
  language: string;
  country_code: string;
  favor_rarer_tags: boolean;
};

export type UploadUserApplicationLogV1Params = {
  appid: number;
  log_type: string;
  version_string: string;
  log_contents: string;
  request_id: number;
};

export type GetApplicationLogDemandV1Params = {
  appid: number;
};

export type InterfaceName = 'IClientStats_1046930' | 'IGCVersion_1046930' | 'IGCVersion_1269260' | 'IGCVersion_1422450' | 'IGCVersion_440' | 'IGCVersion_570' | 'IGCVersion_583950' | 'IGCVersion_730' | 'IPortal2Leaderboards_620' | 'ISteamApps' | 'ISteamBroadcast' | 'ISteamDirectory' | 'ISteamNews' | 'ISteamRemoteStorage' | 'ISteamUserOAuth' | 'ISteamUserStats' | 'ISteamWebAPIUtil' | 'ITFSystem_440' | 'IAuthenticationService' | 'IBroadcastService' | 'IContentServerDirectoryService' | 'IPublishedFileService' | 'IPlayerService' | 'IGameNotificationsService' | 'IWishlistService' | 'IStoreService' | 'IHelpRequestLogsService';

export type MethodName<I extends InterfaceName> = 
  I extends 'IClientStats_1046930' ? 'ReportEvent_v1' :
  I extends 'IGCVersion_1046930' ? 'GetClientVersion_v1' | 'GetServerVersion_v1' :
  I extends 'IGCVersion_1269260' ? 'GetClientVersion_v1' | 'GetServerVersion_v1' :
  I extends 'IGCVersion_1422450' ? 'GetClientVersion_v1' | 'GetServerVersion_v1' :
  I extends 'IGCVersion_440' ? 'GetClientVersion_v1' | 'GetServerVersion_v1' :
  I extends 'IGCVersion_570' ? 'GetClientVersion_v1' | 'GetServerVersion_v1' :
  I extends 'IGCVersion_583950' ? 'GetClientVersion_v1' | 'GetServerVersion_v1' :
  I extends 'IGCVersion_730' ? 'GetServerVersion_v1' :
  I extends 'IPortal2Leaderboards_620' ? 'GetBucketizedData_v1' :
  I extends 'ISteamApps' ? 'GetAppList_v1' | 'GetAppList_v2' | 'GetSDRConfig_v1' | 'GetServersAtAddress_v1' | 'UpToDateCheck_v1' :
  I extends 'ISteamBroadcast' ? 'PlayerStats_v1' | 'ViewerHeartbeat_v1' :
  I extends 'ISteamDirectory' ? 'GetCMList_v1' | 'GetCMListForConnect_v1' | 'GetSteamPipeDomains_v1' :
  I extends 'ISteamNews' ? 'GetNewsForApp_v1' | 'GetNewsForApp_v2' :
  I extends 'ISteamRemoteStorage' ? 'GetCollectionDetails_v1' | 'GetPublishedFileDetails_v1' :
  I extends 'ISteamUserOAuth' ? 'GetTokenDetails_v1' :
  I extends 'ISteamUserStats' ? 'GetGlobalAchievementPercentagesForApp_v1' | 'GetGlobalAchievementPercentagesForApp_v2' | 'GetGlobalStatsForGame_v1' | 'GetNumberOfCurrentPlayers_v1' :
  I extends 'ISteamWebAPIUtil' ? 'GetServerInfo_v1' | 'GetSupportedAPIList_v1' :
  I extends 'ITFSystem_440' ? 'GetWorldStatus_v1' :
  I extends 'IAuthenticationService' ? 'PollAuthSessionStatus_v1' | 'GetAuthSessionInfo_v1' | 'GetAuthSessionRiskInfo_v1' | 'NotifyRiskQuizResults_v1' | 'GetPasswordRSAPublicKey_v1' | 'BeginAuthSessionViaCredentials_v1' | 'UpdateAuthSessionWithSteamGuardCode_v1' | 'BeginAuthSessionViaQR_v1' | 'UpdateAuthSessionWithMobileConfirmation_v1' :
  I extends 'IBroadcastService' ? 'PostGameDataFrameRTMP_v1' :
  I extends 'IContentServerDirectoryService' ? 'GetCDNForVideo_v1' | 'PickSingleContentServer_v1' | 'GetServersForSteamPipe_v1' | 'GetClientUpdateHosts_v1' | 'GetDepotPatchInfo_v1' :
  I extends 'IPublishedFileService' ? 'GetUserVoteSummary_v1' :
  I extends 'IPlayerService' ? 'RecordOfflinePlaytime_v1' :
  I extends 'IGameNotificationsService' ? 'UserCreateSession_v1' | 'UserUpdateSession_v1' | 'UserDeleteSession_v1' :
  I extends 'IWishlistService' ? 'GetWishlistSortedFiltered_v1' | 'GetWishlist_v1' | 'GetWishlistItemCount_v1' :
  I extends 'IStoreService' ? 'GetGamesFollowed_v1' | 'GetGamesFollowedCount_v1' | 'GetRecommendedTagsForUser_v1' :
  I extends 'IHelpRequestLogsService' ? 'UploadUserApplicationLog_v1' | 'GetApplicationLogDemand_v1' :
  never;

/** Utility type to map method names to their generated parameter types */
export type MethodParamsMap = {
  'ReportEvent_v1': ReportEventV1Params;
  'GetClientVersion_v1': GetClientVersionV1Params;
  'GetServerVersion_v1': GetServerVersionV1Params;
  'GetBucketizedData_v1': GetBucketizedDataV1Params;
  'GetAppList_v1': GetAppListV1Params;
  'GetAppList_v2': GetAppListV2Params;
  'GetSDRConfig_v1': GetSDRConfigV1Params;
  'GetServersAtAddress_v1': GetServersAtAddressV1Params;
  'UpToDateCheck_v1': UpToDateCheckV1Params;
  'PlayerStats_v1': PlayerStatsV1Params;
  'ViewerHeartbeat_v1': ViewerHeartbeatV1Params;
  'GetCMList_v1': GetCMListV1Params;
  'GetCMListForConnect_v1': GetCMListForConnectV1Params;
  'GetSteamPipeDomains_v1': GetSteamPipeDomainsV1Params;
  'GetNewsForApp_v1': GetNewsForAppV1Params;
  'GetNewsForApp_v2': GetNewsForAppV2Params;
  'GetCollectionDetails_v1': GetCollectionDetailsV1Params;
  'GetPublishedFileDetails_v1': GetPublishedFileDetailsV1Params;
  'GetTokenDetails_v1': GetTokenDetailsV1Params;
  'GetGlobalAchievementPercentagesForApp_v1': GetGlobalAchievementPercentagesForAppV1Params;
  'GetGlobalAchievementPercentagesForApp_v2': GetGlobalAchievementPercentagesForAppV2Params;
  'GetGlobalStatsForGame_v1': GetGlobalStatsForGameV1Params;
  'GetNumberOfCurrentPlayers_v1': GetNumberOfCurrentPlayersV1Params;
  'GetServerInfo_v1': GetServerInfoV1Params;
  'GetSupportedAPIList_v1': GetSupportedAPIListV1Params;
  'GetWorldStatus_v1': GetWorldStatusV1Params;
  'PollAuthSessionStatus_v1': PollAuthSessionStatusV1Params;
  'GetAuthSessionInfo_v1': GetAuthSessionInfoV1Params;
  'GetAuthSessionRiskInfo_v1': GetAuthSessionRiskInfoV1Params;
  'NotifyRiskQuizResults_v1': NotifyRiskQuizResultsV1Params;
  'GetPasswordRSAPublicKey_v1': GetPasswordRSAPublicKeyV1Params;
  'BeginAuthSessionViaCredentials_v1': BeginAuthSessionViaCredentialsV1Params;
  'UpdateAuthSessionWithSteamGuardCode_v1': UpdateAuthSessionWithSteamGuardCodeV1Params;
  'BeginAuthSessionViaQR_v1': BeginAuthSessionViaQRV1Params;
  'UpdateAuthSessionWithMobileConfirmation_v1': UpdateAuthSessionWithMobileConfirmationV1Params;
  'PostGameDataFrameRTMP_v1': PostGameDataFrameRTMPV1Params;
  'GetCDNForVideo_v1': GetCDNForVideoV1Params;
  'PickSingleContentServer_v1': PickSingleContentServerV1Params;
  'GetServersForSteamPipe_v1': GetServersForSteamPipeV1Params;
  'GetClientUpdateHosts_v1': GetClientUpdateHostsV1Params;
  'GetDepotPatchInfo_v1': GetDepotPatchInfoV1Params;
  'GetUserVoteSummary_v1': GetUserVoteSummaryV1Params;
  'RecordOfflinePlaytime_v1': RecordOfflinePlaytimeV1Params;
  'UserCreateSession_v1': UserCreateSessionV1Params;
  'UserUpdateSession_v1': UserUpdateSessionV1Params;
  'UserDeleteSession_v1': UserDeleteSessionV1Params;
  'GetWishlistSortedFiltered_v1': GetWishlistSortedFilteredV1Params;
  'GetWishlist_v1': GetWishlistV1Params;
  'GetWishlistItemCount_v1': GetWishlistItemCountV1Params;
  'GetGamesFollowed_v1': GetGamesFollowedV1Params;
  'GetGamesFollowedCount_v1': GetGamesFollowedCountV1Params;
  'GetRecommendedTagsForUser_v1': GetRecommendedTagsForUserV1Params;
  'UploadUserApplicationLog_v1': UploadUserApplicationLogV1Params;
  'GetApplicationLogDemand_v1': GetApplicationLogDemandV1Params;
};

/** Metadata for each generated method identifier */
export type MethodInfoMap = {
  'IClientStats_1046930': {
    'ReportEvent_v1': { interface: 'IClientStats_1046930'; name: 'ReportEvent'; version: 1; httpMethod: 'POST'; };
  };
  'IGCVersion_1046930': {
    'GetClientVersion_v1': { interface: 'IGCVersion_1046930'; name: 'GetClientVersion'; version: 1; httpMethod: 'GET'; };
    'GetServerVersion_v1': { interface: 'IGCVersion_1046930'; name: 'GetServerVersion'; version: 1; httpMethod: 'GET'; };
  };
  'IGCVersion_1269260': {
    'GetClientVersion_v1': { interface: 'IGCVersion_1269260'; name: 'GetClientVersion'; version: 1; httpMethod: 'GET'; };
    'GetServerVersion_v1': { interface: 'IGCVersion_1269260'; name: 'GetServerVersion'; version: 1; httpMethod: 'GET'; };
  };
  'IGCVersion_1422450': {
    'GetClientVersion_v1': { interface: 'IGCVersion_1422450'; name: 'GetClientVersion'; version: 1; httpMethod: 'GET'; };
    'GetServerVersion_v1': { interface: 'IGCVersion_1422450'; name: 'GetServerVersion'; version: 1; httpMethod: 'GET'; };
  };
  'IGCVersion_440': {
    'GetClientVersion_v1': { interface: 'IGCVersion_440'; name: 'GetClientVersion'; version: 1; httpMethod: 'GET'; };
    'GetServerVersion_v1': { interface: 'IGCVersion_440'; name: 'GetServerVersion'; version: 1; httpMethod: 'GET'; };
  };
  'IGCVersion_570': {
    'GetClientVersion_v1': { interface: 'IGCVersion_570'; name: 'GetClientVersion'; version: 1; httpMethod: 'GET'; };
    'GetServerVersion_v1': { interface: 'IGCVersion_570'; name: 'GetServerVersion'; version: 1; httpMethod: 'GET'; };
  };
  'IGCVersion_583950': {
    'GetClientVersion_v1': { interface: 'IGCVersion_583950'; name: 'GetClientVersion'; version: 1; httpMethod: 'GET'; };
    'GetServerVersion_v1': { interface: 'IGCVersion_583950'; name: 'GetServerVersion'; version: 1; httpMethod: 'GET'; };
  };
  'IGCVersion_730': {
    'GetServerVersion_v1': { interface: 'IGCVersion_730'; name: 'GetServerVersion'; version: 1; httpMethod: 'GET'; };
  };
  'IPortal2Leaderboards_620': {
    'GetBucketizedData_v1': { interface: 'IPortal2Leaderboards_620'; name: 'GetBucketizedData'; version: 1; httpMethod: 'GET'; };
  };
  'ISteamApps': {
    'GetAppList_v1': { interface: 'ISteamApps'; name: 'GetAppList'; version: 1; httpMethod: 'GET'; };
    'GetAppList_v2': { interface: 'ISteamApps'; name: 'GetAppList'; version: 2; httpMethod: 'GET'; };
    'GetSDRConfig_v1': { interface: 'ISteamApps'; name: 'GetSDRConfig'; version: 1; httpMethod: 'GET'; };
    'GetServersAtAddress_v1': { interface: 'ISteamApps'; name: 'GetServersAtAddress'; version: 1; httpMethod: 'GET'; };
    'UpToDateCheck_v1': { interface: 'ISteamApps'; name: 'UpToDateCheck'; version: 1; httpMethod: 'GET'; };
  };
  'ISteamBroadcast': {
    'PlayerStats_v1': { interface: 'ISteamBroadcast'; name: 'PlayerStats'; version: 1; httpMethod: 'POST'; };
    'ViewerHeartbeat_v1': { interface: 'ISteamBroadcast'; name: 'ViewerHeartbeat'; version: 1; httpMethod: 'GET'; };
  };
  'ISteamDirectory': {
    'GetCMList_v1': { interface: 'ISteamDirectory'; name: 'GetCMList'; version: 1; httpMethod: 'GET'; };
    'GetCMListForConnect_v1': { interface: 'ISteamDirectory'; name: 'GetCMListForConnect'; version: 1; httpMethod: 'GET'; };
    'GetSteamPipeDomains_v1': { interface: 'ISteamDirectory'; name: 'GetSteamPipeDomains'; version: 1; httpMethod: 'GET'; };
  };
  'ISteamNews': {
    'GetNewsForApp_v1': { interface: 'ISteamNews'; name: 'GetNewsForApp'; version: 1; httpMethod: 'GET'; };
    'GetNewsForApp_v2': { interface: 'ISteamNews'; name: 'GetNewsForApp'; version: 2; httpMethod: 'GET'; };
  };
  'ISteamRemoteStorage': {
    'GetCollectionDetails_v1': { interface: 'ISteamRemoteStorage'; name: 'GetCollectionDetails'; version: 1; httpMethod: 'POST'; };
    'GetPublishedFileDetails_v1': { interface: 'ISteamRemoteStorage'; name: 'GetPublishedFileDetails'; version: 1; httpMethod: 'POST'; };
  };
  'ISteamUserOAuth': {
    'GetTokenDetails_v1': { interface: 'ISteamUserOAuth'; name: 'GetTokenDetails'; version: 1; httpMethod: 'GET'; };
  };
  'ISteamUserStats': {
    'GetGlobalAchievementPercentagesForApp_v1': { interface: 'ISteamUserStats'; name: 'GetGlobalAchievementPercentagesForApp'; version: 1; httpMethod: 'GET'; };
    'GetGlobalAchievementPercentagesForApp_v2': { interface: 'ISteamUserStats'; name: 'GetGlobalAchievementPercentagesForApp'; version: 2; httpMethod: 'GET'; };
    'GetGlobalStatsForGame_v1': { interface: 'ISteamUserStats'; name: 'GetGlobalStatsForGame'; version: 1; httpMethod: 'GET'; };
    'GetNumberOfCurrentPlayers_v1': { interface: 'ISteamUserStats'; name: 'GetNumberOfCurrentPlayers'; version: 1; httpMethod: 'GET'; };
  };
  'ISteamWebAPIUtil': {
    'GetServerInfo_v1': { interface: 'ISteamWebAPIUtil'; name: 'GetServerInfo'; version: 1; httpMethod: 'GET'; };
    'GetSupportedAPIList_v1': { interface: 'ISteamWebAPIUtil'; name: 'GetSupportedAPIList'; version: 1; httpMethod: 'GET'; };
  };
  'ITFSystem_440': {
    'GetWorldStatus_v1': { interface: 'ITFSystem_440'; name: 'GetWorldStatus'; version: 1; httpMethod: 'GET'; };
  };
  'IAuthenticationService': {
    'PollAuthSessionStatus_v1': { interface: 'IAuthenticationService'; name: 'PollAuthSessionStatus'; version: 1; httpMethod: 'POST'; };
    'GetAuthSessionInfo_v1': { interface: 'IAuthenticationService'; name: 'GetAuthSessionInfo'; version: 1; httpMethod: 'POST'; };
    'GetAuthSessionRiskInfo_v1': { interface: 'IAuthenticationService'; name: 'GetAuthSessionRiskInfo'; version: 1; httpMethod: 'POST'; };
    'NotifyRiskQuizResults_v1': { interface: 'IAuthenticationService'; name: 'NotifyRiskQuizResults'; version: 1; httpMethod: 'POST'; };
    'GetPasswordRSAPublicKey_v1': { interface: 'IAuthenticationService'; name: 'GetPasswordRSAPublicKey'; version: 1; httpMethod: 'GET'; };
    'BeginAuthSessionViaCredentials_v1': { interface: 'IAuthenticationService'; name: 'BeginAuthSessionViaCredentials'; version: 1; httpMethod: 'POST'; };
    'UpdateAuthSessionWithSteamGuardCode_v1': { interface: 'IAuthenticationService'; name: 'UpdateAuthSessionWithSteamGuardCode'; version: 1; httpMethod: 'POST'; };
    'BeginAuthSessionViaQR_v1': { interface: 'IAuthenticationService'; name: 'BeginAuthSessionViaQR'; version: 1; httpMethod: 'POST'; };
    'UpdateAuthSessionWithMobileConfirmation_v1': { interface: 'IAuthenticationService'; name: 'UpdateAuthSessionWithMobileConfirmation'; version: 1; httpMethod: 'POST'; };
  };
  'IBroadcastService': {
    'PostGameDataFrameRTMP_v1': { interface: 'IBroadcastService'; name: 'PostGameDataFrameRTMP'; version: 1; httpMethod: 'POST'; };
  };
  'IContentServerDirectoryService': {
    'GetCDNForVideo_v1': { interface: 'IContentServerDirectoryService'; name: 'GetCDNForVideo'; version: 1; httpMethod: 'GET'; };
    'PickSingleContentServer_v1': { interface: 'IContentServerDirectoryService'; name: 'PickSingleContentServer'; version: 1; httpMethod: 'GET'; };
    'GetServersForSteamPipe_v1': { interface: 'IContentServerDirectoryService'; name: 'GetServersForSteamPipe'; version: 1; httpMethod: 'GET'; };
    'GetClientUpdateHosts_v1': { interface: 'IContentServerDirectoryService'; name: 'GetClientUpdateHosts'; version: 1; httpMethod: 'GET'; };
    'GetDepotPatchInfo_v1': { interface: 'IContentServerDirectoryService'; name: 'GetDepotPatchInfo'; version: 1; httpMethod: 'GET'; };
  };
  'IPublishedFileService': {
    'GetUserVoteSummary_v1': { interface: 'IPublishedFileService'; name: 'GetUserVoteSummary'; version: 1; httpMethod: 'GET'; };
  };
  'IPlayerService': {
    'RecordOfflinePlaytime_v1': { interface: 'IPlayerService'; name: 'RecordOfflinePlaytime'; version: 1; httpMethod: 'POST'; };
  };
  'IGameNotificationsService': {
    'UserCreateSession_v1': { interface: 'IGameNotificationsService'; name: 'UserCreateSession'; version: 1; httpMethod: 'POST'; };
    'UserUpdateSession_v1': { interface: 'IGameNotificationsService'; name: 'UserUpdateSession'; version: 1; httpMethod: 'POST'; };
    'UserDeleteSession_v1': { interface: 'IGameNotificationsService'; name: 'UserDeleteSession'; version: 1; httpMethod: 'POST'; };
  };
  'IWishlistService': {
    'GetWishlistSortedFiltered_v1': { interface: 'IWishlistService'; name: 'GetWishlistSortedFiltered'; version: 1; httpMethod: 'GET'; };
    'GetWishlist_v1': { interface: 'IWishlistService'; name: 'GetWishlist'; version: 1; httpMethod: 'GET'; };
    'GetWishlistItemCount_v1': { interface: 'IWishlistService'; name: 'GetWishlistItemCount'; version: 1; httpMethod: 'GET'; };
  };
  'IStoreService': {
    'GetGamesFollowed_v1': { interface: 'IStoreService'; name: 'GetGamesFollowed'; version: 1; httpMethod: 'GET'; };
    'GetGamesFollowedCount_v1': { interface: 'IStoreService'; name: 'GetGamesFollowedCount'; version: 1; httpMethod: 'GET'; };
    'GetRecommendedTagsForUser_v1': { interface: 'IStoreService'; name: 'GetRecommendedTagsForUser'; version: 1; httpMethod: 'GET'; };
  };
  'IHelpRequestLogsService': {
    'UploadUserApplicationLog_v1': { interface: 'IHelpRequestLogsService'; name: 'UploadUserApplicationLog'; version: 1; httpMethod: 'POST'; };
    'GetApplicationLogDemand_v1': { interface: 'IHelpRequestLogsService'; name: 'GetApplicationLogDemand'; version: 1; httpMethod: 'POST'; };
  };
};
