/* eslint-disable */
// Generated by generate-api-types.ts. DO NOT EDIT MANUALLY.

export type ReportEventParams = Record<string, never>;

export type GetClientVersionParams = Record<string, never>;

export type GetServerVersionParams = Record<string, never>;

export type GetBucketizedDataParams = {
  leaderboardName: string;
};

export type GetAppListParams = Record<string, never>;

export type GetSDRConfigParams = {
  appid: number;
};

export type GetServersAtAddressParams = {
  addr: string;
};

export type UpToDateCheckParams = {
  appid: number;
  version: number;
};

export type PlayerStatsParams = Record<string, never>;

export type ViewerHeartbeatParams = {
  steamid: number;
  sessionid: number;
  token: number;
  stream?: any | undefined;
};

export type GetCMListParams = {
  cellid: number;
  maxcount?: number | undefined;
};

export type GetCMListForConnectParams = {
  cellid?: number | undefined;
  cmtype?: string | undefined;
  realm?: string | undefined;
  maxcount?: number | undefined;
  qoslevel?: number | undefined;
};

export type GetSteamPipeDomainsParams = Record<string, never>;

export type GetNewsForAppParams = {
  appid: number;
  maxlength?: number | undefined;
  enddate?: number | undefined;
  count?: number | undefined;
  feeds?: string | undefined;
  tags?: string | undefined;
};

export type GetCollectionDetailsParams = {
  collectioncount: number;
  'publishedfileids[0]': number;
};

export type GetPublishedFileDetailsParams = {
  itemcount: number;
  'publishedfileids[0]': number;
};

export type GetTokenDetailsParams = {
  access_token: string;
};

export type GetGlobalAchievementPercentagesForAppParams = {
  gameid: number;
};

export type GetGlobalStatsForGameParams = {
  appid: number;
  count: number;
  'name[0]': string;
  startdate?: number | undefined;
  enddate?: number | undefined;
};

export type GetNumberOfCurrentPlayersParams = {
  appid: number;
};

export type GetServerInfoParams = Record<string, never>;

export type GetSupportedAPIListParams = {
  key?: string | undefined;
};

export type GetWorldStatusParams = Record<string, never>;

export type PollAuthSessionStatusParams = {
  client_id: number;
  request_id: string;
  token_to_revoke: number;
};

export type GetAuthSessionInfoParams = {
  client_id: number;
};

export type GetAuthSessionRiskInfoParams = {
  client_id: number;
  language: number;
};

export type NotifyRiskQuizResultsParams = {
  client_id: number;
  results: any;
  selected_action: string;
  did_confirm_login: boolean;
};

export type GetPasswordRSAPublicKeyParams = {
  account_name: string;
};

export type BeginAuthSessionViaCredentialsParams = {
  device_friendly_name: string;
  account_name: string;
  encrypted_password: string;
  encryption_timestamp: number;
  remember_login: boolean;
  platform_type: any;
  persistence?: any | undefined;
  website_id?: string | undefined;
  device_details: any;
  guard_data: string;
  language: number;
  qos_level?: any | undefined;
};

export type UpdateAuthSessionWithSteamGuardCodeParams = {
  client_id: number;
  steamid: number;
  code: string;
  code_type: any;
};

export type BeginAuthSessionViaQRParams = {
  device_friendly_name: string;
  platform_type: any;
  device_details: any;
  website_id?: string | undefined;
};

export type UpdateAuthSessionWithMobileConfirmationParams = {
  version: any;
  client_id: number;
  steamid: number;
  signature: string;
  confirm?: boolean | undefined;
  persistence?: any | undefined;
};

export type PostGameDataFrameRTMPParams = {
  appid: number;
  steamid: number;
  rtmp_token: string;
  frame_data: string;
};

export type GetCDNForVideoParams = {
  property_type: any;
  client_ip: string;
  client_region: string;
};

export type PickSingleContentServerParams = {
  property_type: any;
  cell_id: number;
  client_ip: string;
};

export type GetServersForSteamPipeParams = {
  cell_id: number;
  max_servers?: number | undefined;
  ip_override?: string | undefined;
  launcher_type?: any | undefined;
  ipv6_public?: string | undefined;
  current_connections: any;
};

export type GetClientUpdateHostsParams = {
  cached_signature: string;
};

export type GetDepotPatchInfoParams = {
  appid: number;
  depotid: number;
  source_manifestid: number;
  target_manifestid: number;
};

export type GetUserVoteSummaryParams = {
  publishedfileids: number;
};

export type RecordOfflinePlaytimeParams = {
  steamid: number;
  ticket: string;
  play_sessions: any;
};

export type UserCreateSessionParams = {
  appid: number;
  context: number;
  title: any;
  users: any;
  steamid: number;
};

export type UserUpdateSessionParams = {
  sessionid: number;
  appid: number;
  title: any;
  users: any;
  steamid: number;
};

export type UserDeleteSessionParams = {
  sessionid: number;
  appid: number;
  steamid: number;
};

export type GetWishlistSortedFilteredParams = {
  steamid: number;
  context: any;
  data_request: any;
  sort_order?: any | undefined;
  filters: any;
  start_index?: any | undefined;
  page_size?: any | undefined;
};

export type GetWishlistParams = {
  steamid: number;
};

export type GetWishlistItemCountParams = {
  steamid: number;
};

export type GetGamesFollowedParams = {
  steamid: number;
};

export type GetGamesFollowedCountParams = {
  steamid: number;
};

export type GetRecommendedTagsForUserParams = {
  language: string;
  country_code: string;
  favor_rarer_tags: boolean;
};

export type UploadUserApplicationLogParams = {
  appid: number;
  log_type: string;
  version_string: string;
  log_contents: string;
  request_id: number;
};

export type GetApplicationLogDemandParams = {
  appid: number;
};

export type InterfaceName = 'IClientStats_1046930' | 'IGCVersion_1046930' | 'IGCVersion_1269260' | 'IGCVersion_1422450' | 'IGCVersion_440' | 'IGCVersion_570' | 'IGCVersion_583950' | 'IGCVersion_730' | 'IPortal2Leaderboards_620' | 'ISteamApps' | 'ISteamBroadcast' | 'ISteamDirectory' | 'ISteamNews' | 'ISteamRemoteStorage' | 'ISteamUserOAuth' | 'ISteamUserStats' | 'ISteamWebAPIUtil' | 'ITFSystem_440' | 'IAuthenticationService' | 'IBroadcastService' | 'IContentServerDirectoryService' | 'IPublishedFileService' | 'IPlayerService' | 'IGameNotificationsService' | 'IWishlistService' | 'IStoreService' | 'IHelpRequestLogsService';

export type MethodName<I extends InterfaceName> = 
  I extends 'IClientStats_1046930' ? 'ReportEvent' :
  I extends 'IGCVersion_1046930' ? 'GetClientVersion' | 'GetServerVersion' :
  I extends 'IGCVersion_1269260' ? 'GetClientVersion' | 'GetServerVersion' :
  I extends 'IGCVersion_1422450' ? 'GetClientVersion' | 'GetServerVersion' :
  I extends 'IGCVersion_440' ? 'GetClientVersion' | 'GetServerVersion' :
  I extends 'IGCVersion_570' ? 'GetClientVersion' | 'GetServerVersion' :
  I extends 'IGCVersion_583950' ? 'GetClientVersion' | 'GetServerVersion' :
  I extends 'IGCVersion_730' ? 'GetServerVersion' :
  I extends 'IPortal2Leaderboards_620' ? 'GetBucketizedData' :
  I extends 'ISteamApps' ? 'GetAppList' | 'GetAppList' | 'GetSDRConfig' | 'GetServersAtAddress' | 'UpToDateCheck' :
  I extends 'ISteamBroadcast' ? 'PlayerStats' | 'ViewerHeartbeat' :
  I extends 'ISteamDirectory' ? 'GetCMList' | 'GetCMListForConnect' | 'GetSteamPipeDomains' :
  I extends 'ISteamNews' ? 'GetNewsForApp' | 'GetNewsForApp' :
  I extends 'ISteamRemoteStorage' ? 'GetCollectionDetails' | 'GetPublishedFileDetails' :
  I extends 'ISteamUserOAuth' ? 'GetTokenDetails' :
  I extends 'ISteamUserStats' ? 'GetGlobalAchievementPercentagesForApp' | 'GetGlobalAchievementPercentagesForApp' | 'GetGlobalStatsForGame' | 'GetNumberOfCurrentPlayers' :
  I extends 'ISteamWebAPIUtil' ? 'GetServerInfo' | 'GetSupportedAPIList' :
  I extends 'ITFSystem_440' ? 'GetWorldStatus' :
  I extends 'IAuthenticationService' ? 'PollAuthSessionStatus' | 'GetAuthSessionInfo' | 'GetAuthSessionRiskInfo' | 'NotifyRiskQuizResults' | 'GetPasswordRSAPublicKey' | 'BeginAuthSessionViaCredentials' | 'UpdateAuthSessionWithSteamGuardCode' | 'BeginAuthSessionViaQR' | 'UpdateAuthSessionWithMobileConfirmation' :
  I extends 'IBroadcastService' ? 'PostGameDataFrameRTMP' :
  I extends 'IContentServerDirectoryService' ? 'GetCDNForVideo' | 'PickSingleContentServer' | 'GetServersForSteamPipe' | 'GetClientUpdateHosts' | 'GetDepotPatchInfo' :
  I extends 'IPublishedFileService' ? 'GetUserVoteSummary' :
  I extends 'IPlayerService' ? 'RecordOfflinePlaytime' :
  I extends 'IGameNotificationsService' ? 'UserCreateSession' | 'UserUpdateSession' | 'UserDeleteSession' :
  I extends 'IWishlistService' ? 'GetWishlistSortedFiltered' | 'GetWishlist' | 'GetWishlistItemCount' :
  I extends 'IStoreService' ? 'GetGamesFollowed' | 'GetGamesFollowedCount' | 'GetRecommendedTagsForUser' :
  I extends 'IHelpRequestLogsService' ? 'UploadUserApplicationLog' | 'GetApplicationLogDemand' :
  never;

/** Utility type to map method names to their generated parameter types */
export type MethodParamsMap = {
  'ReportEvent': ReportEventParams;
  'GetClientVersion': GetClientVersionParams;
  'GetServerVersion': GetServerVersionParams;
  'GetBucketizedData': GetBucketizedDataParams;
  'GetAppList': GetAppListParams;
  'GetSDRConfig': GetSDRConfigParams;
  'GetServersAtAddress': GetServersAtAddressParams;
  'UpToDateCheck': UpToDateCheckParams;
  'PlayerStats': PlayerStatsParams;
  'ViewerHeartbeat': ViewerHeartbeatParams;
  'GetCMList': GetCMListParams;
  'GetCMListForConnect': GetCMListForConnectParams;
  'GetSteamPipeDomains': GetSteamPipeDomainsParams;
  'GetNewsForApp': GetNewsForAppParams;
  'GetCollectionDetails': GetCollectionDetailsParams;
  'GetPublishedFileDetails': GetPublishedFileDetailsParams;
  'GetTokenDetails': GetTokenDetailsParams;
  'GetGlobalAchievementPercentagesForApp': GetGlobalAchievementPercentagesForAppParams;
  'GetGlobalStatsForGame': GetGlobalStatsForGameParams;
  'GetNumberOfCurrentPlayers': GetNumberOfCurrentPlayersParams;
  'GetServerInfo': GetServerInfoParams;
  'GetSupportedAPIList': GetSupportedAPIListParams;
  'GetWorldStatus': GetWorldStatusParams;
  'PollAuthSessionStatus': PollAuthSessionStatusParams;
  'GetAuthSessionInfo': GetAuthSessionInfoParams;
  'GetAuthSessionRiskInfo': GetAuthSessionRiskInfoParams;
  'NotifyRiskQuizResults': NotifyRiskQuizResultsParams;
  'GetPasswordRSAPublicKey': GetPasswordRSAPublicKeyParams;
  'BeginAuthSessionViaCredentials': BeginAuthSessionViaCredentialsParams;
  'UpdateAuthSessionWithSteamGuardCode': UpdateAuthSessionWithSteamGuardCodeParams;
  'BeginAuthSessionViaQR': BeginAuthSessionViaQRParams;
  'UpdateAuthSessionWithMobileConfirmation': UpdateAuthSessionWithMobileConfirmationParams;
  'PostGameDataFrameRTMP': PostGameDataFrameRTMPParams;
  'GetCDNForVideo': GetCDNForVideoParams;
  'PickSingleContentServer': PickSingleContentServerParams;
  'GetServersForSteamPipe': GetServersForSteamPipeParams;
  'GetClientUpdateHosts': GetClientUpdateHostsParams;
  'GetDepotPatchInfo': GetDepotPatchInfoParams;
  'GetUserVoteSummary': GetUserVoteSummaryParams;
  'RecordOfflinePlaytime': RecordOfflinePlaytimeParams;
  'UserCreateSession': UserCreateSessionParams;
  'UserUpdateSession': UserUpdateSessionParams;
  'UserDeleteSession': UserDeleteSessionParams;
  'GetWishlistSortedFiltered': GetWishlistSortedFilteredParams;
  'GetWishlist': GetWishlistParams;
  'GetWishlistItemCount': GetWishlistItemCountParams;
  'GetGamesFollowed': GetGamesFollowedParams;
  'GetGamesFollowedCount': GetGamesFollowedCountParams;
  'GetRecommendedTagsForUser': GetRecommendedTagsForUserParams;
  'UploadUserApplicationLog': UploadUserApplicationLogParams;
  'GetApplicationLogDemand': GetApplicationLogDemandParams;
};
